# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='address',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
